import { NextRequest, NextResponse } from 'next/server'

export async function GET(request: NextRequest) {
  // Get dialogue from query parameters if available
  const { searchParams } = new URL(request.url)
  const dialogue = searchParams.get('dialogue') || '"Sample dialogue text"'

  // Split dialogue into lines for better display (max 20 characters per line)
  const words = dialogue.replace(/"/g, '').split(' ')
  const lines = []
  let currentLine = ''

  for (const word of words) {
    if ((currentLine + word).length <= 20) {
      currentLine += (currentLine ? ' ' : '') + word
    } else {
      if (currentLine) lines.push(currentLine)
      currentLine = word
    }
  }
  if (currentLine) lines.push(currentLine)

  // Limit to 3 lines max
  const displayLines = lines.slice(0, 3)

  const svgContent = `
    <svg width="400" height="300" xmlns="http://www.w3.org/2000/svg">
      <rect width="400" height="300" fill="#f8fafc" stroke="#e2e8f0" stroke-width="2"/>

      <!-- Comic panel border -->
      <rect x="20" y="20" width="360" height="260" fill="white" stroke="#1e293b" stroke-width="3"/>

      <!-- Title -->
      <text x="200" y="50" text-anchor="middle" font-family="serif" font-size="16" font-weight="bold" fill="#1e293b">
        MOCKR POLITICAL CARTOON
      </text>

      <!-- Simple character (politician) -->
      <circle cx="120" cy="150" r="30" fill="none" stroke="#1e293b" stroke-width="2"/>
      <circle cx="115" cy="145" r="2" fill="#1e293b"/>
      <circle cx="125" cy="145" r="2" fill="#1e293b"/>
      <path d="M 110 160 Q 120 170 130 160" stroke="#1e293b" stroke-width="2" fill="none"/>

      <!-- Body -->
      <rect x="100" y="180" width="40" height="60" fill="none" stroke="#1e293b" stroke-width="2"/>

      <!-- Enhanced Speech bubble -->
      <ellipse cx="280" cy="120" rx="90" ry="50" fill="white" stroke="#1e293b" stroke-width="2"/>
      <polygon points="210,140 180,160 220,155" fill="white" stroke="#1e293b" stroke-width="2"/>

      <!-- Dynamic Speech text -->
      ${displayLines.map((line, index) =>
        `<text x="280" y="${105 + (index * 15)}" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#1e293b">"${line}"</text>`
      ).join('')}

      <!-- Ground line -->
      <line x1="40" y1="250" x2="360" y2="250" stroke="#1e293b" stroke-width="1"/>

      <!-- Watermark -->
      <text x="350" y="290" text-anchor="end" font-family="sans-serif" font-size="10" fill="#64748b">
        Generated by Mockr AI
      </text>
    </svg>
  `

  return new NextResponse(svgContent, {
    headers: {
      'Content-Type': 'image/svg+xml',
      'Cache-Control': 'no-cache'
    }
  })
}