'use client'

import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Navigation */}
      <nav className="w-full px-6 py-4 lg:py-6 bg-white border-b border-neutral-200 sticky top-0 z-50">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center space-x-3">
            <ArrowLeft className="w-5 h-5 text-neutral-600 hover:text-neutral-900 transition-colors" />
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-gradient-to-r from-neutral-800 to-neutral-700 rounded-xl flex items-center justify-center shadow-sm">
                <span className="text-white font-bold text-xl">M</span>
              </div>
              <span className="text-2xl font-bold bg-gradient-to-r from-neutral-800 to-neutral-700 bg-clip-text text-transparent">Mockr</span>
            </div>
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-12 lg:py-16">
        <h1 className="text-4xl lg:text-5xl font-bold text-neutral-900 mb-4">Terms of Service</h1>
        <p className="text-neutral-600 mb-8">Last updated: January 2025</p>

        <div className="prose prose-neutral max-w-none space-y-6 text-neutral-700 leading-relaxed">
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Agreement to Terms</h2>
            <p>
              By accessing and using Mockr, you agree to be bound by these Terms of Service and all applicable laws
              and regulations. If you do not agree with any of these terms, you are prohibited from using this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Description of Service</h2>
            <p>
              Mockr is an AI-powered platform that enables users to create political cartoons based on textual
              descriptions. The service uses artificial intelligence to generate satirical quotes, visual descriptions,
              and cartoon images in editorial style.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Account Registration</h2>
            <p>
              To use Mockr, you must:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Be at least 13 years of age</li>
              <li>Provide accurate and complete registration information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Accept responsibility for all activities under your account</li>
              <li>Notify us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Acceptable Use</h2>

            <h3 className="text-xl font-semibold text-neutral-900 mb-3 mt-4">You May:</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Create political satire and social commentary</li>
              <li>Share your created comics on social media</li>
              <li>Use comics for personal, educational, or editorial purposes</li>
              <li>Provide feedback and suggestions</li>
            </ul>

            <h3 className="text-xl font-semibold text-neutral-900 mb-3 mt-4">You May Not:</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Create content that incites violence or hatred</li>
              <li>Generate content that harasses or threatens individuals</li>
              <li>Use the service to spread misinformation or propaganda</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Attempt to bypass usage limits or abuse the service</li>
              <li>Use automated systems to access the service excessively</li>
              <li>Reverse engineer or copy our AI models</li>
              <li>Create content that infringes on intellectual property rights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Intellectual Property</h2>

            <h3 className="text-xl font-semibold text-neutral-900 mb-3 mt-4">Your Content</h3>
            <p>
              You retain all rights to the political situations you describe. However, by using Mockr, you grant us
              a license to process your input to generate cartoons.
            </p>

            <h3 className="text-xl font-semibold text-neutral-900 mb-3 mt-4">Generated Content</h3>
            <p>
              Comics generated by Mockr are created using AI and may be used by you for personal, editorial, or
              commercial purposes, subject to these terms. However:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI-generated content may have unique copyright considerations</li>
              <li>You are responsible for ensuring your use complies with applicable laws</li>
              <li>Mockr retains the right to use anonymized data to improve our service</li>
            </ul>

            <h3 className="text-xl font-semibold text-neutral-900 mb-3 mt-4">Mockr Platform</h3>
            <p>
              The Mockr platform, including its design, features, and underlying technology, is protected by copyright
              and other intellectual property laws. You may not copy, modify, or distribute any part of our platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Usage Limits</h2>
            <p>
              Mockr may impose usage limits to ensure fair access for all users:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Daily generation limits may apply</li>
              <li>Rate limiting may be enforced to prevent abuse</li>
              <li>Limits may vary based on account type and service tier</li>
              <li>We reserve the right to modify limits at our discretion</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Disclaimer of Warranties</h2>
            <p>
              Mockr is provided &quot;as is&quot; without any warranties, express or implied. We do not guarantee:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Uninterrupted or error-free service</li>
              <li>Accuracy or reliability of generated content</li>
              <li>Suitability for any particular purpose</li>
              <li>Freedom from bugs or technical issues</li>
            </ul>
            <p>
              AI-generated content may occasionally produce unexpected or inappropriate results. Users are responsible
              for reviewing content before sharing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Mockr and its operators shall not be liable for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Indirect, incidental, or consequential damages</li>
              <li>Loss of data, profits, or business opportunities</li>
              <li>Damages resulting from use or inability to use the service</li>
              <li>Any content generated using our platform</li>
              <li>Third-party actions or claims related to your use</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Mockr from any claims, damages, or expenses arising from:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your use of the service</li>
              <li>Content you create or share</li>
              <li>Violation of these terms</li>
              <li>Infringement of third-party rights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Content Moderation</h2>
            <p>
              While we support free expression and satire, Mockr reserves the right to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Review reported content</li>
              <li>Remove content that violates these terms</li>
              <li>Suspend or terminate accounts for violations</li>
              <li>Implement AI safety filters to prevent harmful content</li>
            </ul>
            <p>
              We strive to balance creative freedom with responsible platform management.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Third-Party Services</h2>
            <p>
              Mockr integrates with third-party services for authentication, AI generation, and hosting. Your use of
              these services is subject to their respective terms and conditions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Termination</h2>
            <p>
              We may terminate or suspend your access immediately, without prior notice, for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Violation of these Terms of Service</li>
              <li>Abusive or fraudulent behavior</li>
              <li>At our discretion for operational reasons</li>
            </ul>
            <p>
              You may terminate your account at any time by contacting us or through account settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Changes will be effective immediately upon
              posting to our website. Your continued use of Mockr after changes constitutes acceptance of the
              updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with applicable laws, without regard to
              conflict of law provisions. Any disputes shall be resolved in appropriate courts.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">Contact Information</h2>
            <p>
              For questions about these Terms of Service, please contact us at{' '}
              <a href="mailto:support@mockr.art" className="text-neutral-900 hover:underline font-semibold">support@mockr.art</a>{' '}
              or use the Feedback button in the app.
            </p>
          </section>

          <section className="pt-6 border-t border-neutral-200">
            <p className="text-sm text-neutral-600">
              By using Mockr, you acknowledge that you have read, understood, and agree to be bound by these
              Terms of Service.
            </p>
          </section>
        </div>

        {/* Back Button */}
        <div className="mt-12">
          <Link
            href="/"
            className="inline-flex items-center space-x-2 bg-gradient-to-r from-neutral-800 to-neutral-700 hover:from-neutral-900 hover:to-neutral-800 text-white font-semibold py-3 px-6 rounded-xl transition-all shadow-sm hover:shadow-md"
          >
            <ArrowLeft className="w-5 h-5" />
            <span>Back to Home</span>
          </Link>
        </div>
      </div>
    </div>
  )
}
